# Generated by Django 4.1.5 on 2023-01-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_alter_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default=True, max_length=15),
            preserve_default=False,
        ),
    ]
