# Generated by Django 4.1.5 on 2023-01-19 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='persons.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='persons.faculty'),
            preserve_default=False,
        ),
    ]
