# Generated by Django 4.1.5 on 2023-01-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=15),
        ),
    ]
