# Generated by Django 4.1.5 on 2023-01-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('ND', 'Nd'), ('HND', 'Hnd')], default=True, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
