# Generated by Django 3.2.18 on 2023-03-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='source_code',
            field=models.FileField(default=True, upload_to='source/'),
            preserve_default=False,
        ),
    ]
