# Generated by Django 3.2.18 on 2023-03-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_student_source_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dayo',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
